#!/usr/bin/env python3
"""
收集 GitHub 上热门的 DevOps 相关项目和技能
每 6 小时执行一次，更新 trending.md
"""

import json
import requests
from datetime import datetime
import os

def fetch_github_trending():
    """
    获取 GitHub Trending 页面内容
    由于 GitHub Trending 没有官方 API，我们通过搜索 API 获取热门 DevOps 项目
    """
    
    # 使用 GitHub Search API 搜索 DevOps 相关热门项目
    query = "topic:devops stars:>1000 pushed:>2025-01-01"
    
    headers = {
        "Accept": "application/vnd.github.v3+json",
        "User-Agent": "DevOps-Trending-Collector"
    }
    
    # 如果有 GitHub Token 就使用
    github_token = os.environ.get("GITHUB_TOKEN")
    if github_token:
        headers["Authorization"] = f"token {github_token}"
    
    results = []
    
    try:
        # 搜索 DevOps 相关项目
        url = f"https://api.github.com/search/repositories?q={query}&sort=stars&order=desc&per_page=20"
        response = requests.get(url, headers=headers, timeout=30)
        
        if response.status_code == 200:
            data = response.json()
            items = data.get("items", [])
            
            for item in items[:15]:
                results.append({
                    "name": item["full_name"],
                    "description": item.get("description", "暂无描述"),
                    "url": item["html_url"],
                    "stars": item["stargazers_count"],
                    "language": item.get("language", "Unknown"),
                    "topics": item.get("topics", [])[:5],
                    "updated_at": item.get("updated_at", "")[:10]
                })
    except Exception as e:
        print(f"Error fetching GitHub trending: {e}")
    
    return results

def generate_markdown(trending_items):
    """生成 Markdown 格式的总结报告"""
    
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    md_content = f"""# 🔥 GitHub DevOps Trending Projects

**更新时间**: {now} (每 6 小时更新)

---

## 热门项目 Top 15

| 排名 | 项目名称 | Stars | 语言 | 最近更新 |
|------|----------|-------|------|----------|
"""
    
    for i, item in enumerate(trending_items, 1):
        topics_str = " ".join([f"`{t}`" for t in item.get("topics", [])[:3]])
        md_content += f"| {i} | [{item['name']}]({item['url']})<br/>{item['description'][:50]}... | ⭐ {item['stars']:,} | {item['language']} | {item['updated_at']} |\n"
    
    md_content += f"""
---

## 详细说明

"""
    
    for i, item in enumerate(trending_items, 1):
        topics_str = ", ".join(item.get("topics", [])[:5])
        md_content += f"""
### {i}. [{item['name']}]({item['url']})

- **Stars**: {item['stars']:,}
- **Language**: {item['language']}
- **Topics**: {topics_str}
- **Last Updated**: {item['updated_at']}
- **Description**: {item['description']}

---
"""
    
    md_content += f"""
## 数据来源

- GitHub Search API
- 搜索条件：topic:devops stars:>1000
- 排序：按 Star 数降序

## 自动更新

本报告每 6 小时自动更新一次。

---
*Generated by DevOps Trending Collector*
"""
    
    return md_content

def main():
    workspace_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    output_file = os.path.join(workspace_dir, "DevOps", "trending.md")
    
    print(f"Fetching GitHub DevOps trending projects...")
    trending_items = fetch_github_trending()
    
    if trending_items:
        md_content = generate_markdown(trending_items)
        
        with open(output_file, "w", encoding="utf-8") as f:
            f.write(md_content)
        
        print(f"Successfully updated {output_file}")
        print(f"Collected {len(trending_items)} projects")
    else:
        print("No trending items found or API error occurred")

if __name__ == "__main__":
    main()
